package com.gymora.ui.theme

import androidx.compose.ui.graphics.Color

// Light palette
val PrimaryLight = Color(0xFF1B6B4F)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFA5F2CF)
val OnPrimaryContainerLight = Color(0xFF002115)
val SecondaryLight = Color(0xFF4D6357)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCFE8D9)
val OnSecondaryContainerLight = Color(0xFF0A1F16)
val TertiaryLight = Color(0xFF3D6373)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFC1E8FB)
val OnTertiaryContainerLight = Color(0xFF001F29)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFFBFDFA)
val OnBackgroundLight = Color(0xFF191C1A)
val SurfaceLight = Color(0xFFFBFDFA)
val OnSurfaceLight = Color(0xFF191C1A)
val SurfaceVariantLight = Color(0xFFDBE5DD)
val OnSurfaceVariantLight = Color(0xFF404943)
val OutlineLight = Color(0xFF707973)

// Dark palette — gym-comfortable: low-luminance surfaces with readable contrast
// (FR-051, PRD-§40).
val PrimaryDark = Color(0xFF8AD6B4)
val OnPrimaryDark = Color(0xFF003826)
val PrimaryContainerDark = Color(0xFF005139)
val OnPrimaryContainerDark = Color(0xFFA5F2CF)
val SecondaryDark = Color(0xFFB4CCBD)
val OnSecondaryDark = Color(0xFF20352A)
val SecondaryContainerDark = Color(0xFF364B40)
val OnSecondaryContainerDark = Color(0xFFCFE8D9)
val TertiaryDark = Color(0xFFA5CCDE)
val OnTertiaryDark = Color(0xFF073543)
val TertiaryContainerDark = Color(0xFF244C5B)
val OnTertiaryContainerDark = Color(0xFFC1E8FB)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF111412)
val OnBackgroundDark = Color(0xFFE1E3DF)
val SurfaceDark = Color(0xFF111412)
val OnSurfaceDark = Color(0xFFE1E3DF)
val SurfaceVariantDark = Color(0xFF404943)
val OnSurfaceVariantDark = Color(0xFFBFC9C1)
val OutlineDark = Color(0xFF8A938C)
